repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff-check
        entry: ruff check --fix --force-exclude
        language: python
        types: [python]
        require_serial: true
        stages: [pre-commit]
        additional_dependencies: [ruff]

      - id: ruff-format
        name: ruff-format
        entry: ruff format --force-exclude
        language: python
        types: [python]
        require_serial: true
        stages: [pre-commit]
        additional_dependencies: [ruff]

      - id: python-compile
        name: python-compile
        entry: python -m py_compile
        language: system
        types: [python]
        stages: [pre-commit]
        pass_filenames: true
